/* Shared API client + formatting helpers for both pages.

   The backend (web/app.py) serves its JSON on http://127.0.0.1:8080 with CORS open, and these
   pages are normally served from the same origin, so BASE is "" and every call is same-origin.
   Override for a split setup with ?api=http://host:port (remembered), or window.AUDITOR_API. */

const API = (() => {
  const q = new URLSearchParams(location.search).get('api');
  if (q !== null) {
    if (q) localStorage.setItem('auditor.api', q);
    else localStorage.removeItem('auditor.api');
  }
  if (window.AUDITOR_API) return window.AUDITOR_API;
  const saved = localStorage.getItem('auditor.api');
  if (saved) return saved.replace(/\/$/, '');
  // Opened as a file:// page, or from a static server on another port: assume the default backend.
  if (location.protocol === 'file:' || location.port === '5500') return 'http://127.0.0.1:8080';
  return '';
})();

async function api(path, opts = {}) {
  let res;
  try {
    res = await fetch(API + path, opts);
  } catch (e) {
    throw new Error(`cannot reach the backend at ${API || location.origin} — is it running? (${e.message})`);
  }
  const text = await res.text();
  let body;
  try { body = text ? JSON.parse(text) : {}; } catch { body = { detail: text.slice(0, 300) }; }
  if (!res.ok) throw new Error(body.detail || body.error || `${res.status} ${res.statusText}`);
  return body;
}

const apiGet = (path) => api(path);
const apiPost = (path, body) =>
  api(path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });

/* ---- formatting ---- */

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

/** Rupees, Indian digit grouping, minus sign for negatives. Display only — Python does the maths. */
function rs(x) {
  if (x === null || x === undefined || x === '') return '—';
  const n = Number(x);
  if (!Number.isFinite(n)) return '—';
  const a = Math.abs(n);
  const body = Math.abs(a - Math.round(a)) < 0.005
    ? Math.round(a).toLocaleString('en-IN')
    : a.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  return (n < 0 ? '−₹' : '₹') + body;
}

/** Signed rupees, for a predicted-minus-actual delta where the sign carries the meaning. */
function rsDelta(x) {
  if (x === null || x === undefined) return '—';
  const n = Number(x);
  if (!Number.isFinite(n)) return '—';
  if (Math.abs(n) < 0.005) return '₹0';
  return (n > 0 ? '+' : '−') + rs(Math.abs(n)).replace('−', '');
}

function shortTime(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d)) return String(iso);
  return d.toLocaleString(undefined, { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' });
}

const CHECK_LABELS = {
  basket_sneaking: 'basket sneaking',
  drip_pricing: 'drip pricing',
  misleading_discount: 'misleading discount',
  price_change: 'price change',
  unexplained_gap: 'unexplained gap',
  vanished_discount: 'vanished discount',
};
const checkLabel = (c) => CHECK_LABELS[c] || String(c || '').replace(/_/g, ' ');

/* ---- small DOM helpers ---- */

const $ = (sel, root = document) => root.querySelector(sel);
const $$ = (sel, root = document) => [...root.querySelectorAll(sel)];

function banner(el, msg, kind = 'err') {
  el.innerHTML = msg ? `<div class="banner ${kind}">${esc(msg)}</div>` : '';
}

/** Warn once, on every page, if the backend is the mock rather than the real thing. */
async function checkHealth(slot) {
  try {
    const h = await apiGet('/api/health');
    if (h.mock) {
      slot.innerHTML = `<div class="banner">Mock backend — every number on this page is fake,
        generated by <span class="mono">web/ui/mock_api.py</span> from the answer keys. Start
        <span class="mono">web.app</span> for real runs.</div>`;
    } else if (h.mode === 'test') {
      slot.innerHTML = `<div class="banner">Backend is in <b>test</b> mode: runs go through the Claude Code
        login and are excluded from the eval table. Use <span class="mono">AUDITOR_MODE=prod</span> for
        anything that goes in the report.</div>`;
    }
    return h;
  } catch (e) {
    banner(slot, e.message, 'err');
    return null;
  }
}
