/* Shared API client + formatting helpers for both pages.

   The backend (web/app.py) serves its JSON on http://127.0.0.1:8080 with CORS open, and these
   pages are normally served from the same origin, so BASE is "" and every call is same-origin.
   Override for a split setup with ?api=http://host:port (remembered), or window.AUDITOR_API. */

const API = (() => {
  const q = new URLSearchParams(location.search).get('api');
  if (q !== null) {
    if (q) localStorage.setItem('auditor.api', q);
    else localStorage.removeItem('auditor.api');
  }
  if (window.AUDITOR_API) return window.AUDITOR_API;
  const saved = localStorage.getItem('auditor.api');
  if (saved) return saved.replace(/\/$/, '');
  // Opened as a file:// page, or from a static server on another port: assume the default backend.
  if (location.protocol === 'file:' || location.port === '5500') return 'http://127.0.0.1:8080';
  return '';
})();

async function api(path, opts = {}) {
  let res;
  try {
    res = await fetch(API + path, opts);
  } catch (e) {
    throw new Error(`cannot reach the backend at ${API || location.origin} — is it running? (${e.message})`);
  }
  const text = await res.text();
  let body;
  try { body = text ? JSON.parse(text) : {}; } catch { body = { detail: text.slice(0, 300) }; }
  if (!res.ok) throw new Error(body.detail || body.error || `${res.status} ${res.statusText}`);
  return body;
}

const apiGet = (path) => api(path);
const apiPost = (path, body) =>
  api(path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });

/* ---- formatting ---- */

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

/** Rupees, Indian digit grouping, minus sign for negatives. Display only — Python does the maths. */
function rs(x) {
  if (x === null || x === undefined || x === '') return '—';
  const n = Number(x);
  if (!Number.isFinite(n)) return '—';
  const a = Math.abs(n);
  const body = Math.abs(a - Math.round(a)) < 0.005
    ? Math.round(a).toLocaleString('en-IN')
    : a.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  return (n < 0 ? '−₹' : '₹') + body;
}

/** Signed rupees, for a predicted-minus-actual delta where the sign carries the meaning. */
function rsDelta(x) {
  if (x === null || x === undefined) return '—';
  const n = Number(x);
  if (!Number.isFinite(n)) return '—';
  if (Math.abs(n) < 0.005) return '₹0';
  return (n > 0 ? '+' : '−') + rs(Math.abs(n)).replace('−', '');
}

function shortTime(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d)) return String(iso);
  return d.toLocaleString(undefined, { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' });
}

const CHECK_LABELS = {
  basket_sneaking: 'basket sneaking',
  drip_pricing: 'drip pricing',
  misleading_discount: 'misleading discount',
  price_change: 'price change',
  unexplained_gap: 'unexplained gap',
  vanished_discount: 'vanished discount',
};
const checkLabel = (c) => CHECK_LABELS[c] || String(c || '').replace(/_/g, ' ');

/* ---- small DOM helpers ---- */

const $ = (sel, root = document) => root.querySelector(sel);
const $$ = (sel, root = document) => [...root.querySelectorAll(sel)];

/** A status message. Kind is info | warn | bad | good; the glyph means status never rides on
    colour alone, which matters because the reserved red and green are close under CVD. */
const GLYPH = { info: 'ⓘ', warn: '▲', bad: '✕', good: '✓' };
function notice(el, msg, kind = 'bad') {
  el.innerHTML = msg
    ? `<div class="notice ${kind}"><span class="g" aria-hidden="true">${GLYPH[kind]}</span><span>${msg}</span></div>`
    : '';
}
const noticeText = (el, msg, kind) => notice(el, esc(msg), kind);

/** Pill with a glyph and a word — never a bare colour. */
const badge = (kind, glyph, text) =>
  `<span class="badge ${kind}">${glyph ? `<span class="g" aria-hidden="true">${glyph}</span>` : ''}${esc(text)}</span>`;

/** Backend identity in the sidebar, plus a page notice when it is not a real prod backend. */
async function checkHealth(sideSlot, noticeSlot) {
  try {
    const h = await apiGet('/api/health');
    const kind = h.mock ? 'warning' : h.mode === 'prod' ? 'good' : 'warning';
    const label = h.mock ? 'Mock data' : `${h.mode} mode`;
    sideSlot.innerHTML = `
      <div class="line"><span class="dot ${kind}"></span><span>${esc(label)}</span></div>
      <div class="mono">${esc(API || location.host)}</div>`;

    if (noticeSlot && h.mock) {
      notice(noticeSlot, `<b>Mock backend.</b> Every number here is generated by
        <span class="mono">web/ui/mock_api.py</span> from the answer keys — nothing has actually run.
        Start <span class="mono">web.app</span> for real audits.`, 'warn');
    } else if (noticeSlot && h.mode === 'test') {
      notice(noticeSlot, `<b>Test mode.</b> Runs go through the Claude Code login and are excluded
        from the eval table. Use <span class="mono">AUDITOR_MODE=prod</span> for anything that goes
        in the report.`, 'warn');
    }
    return h;
  } catch (e) {
    sideSlot.innerHTML = `<div class="line"><span class="dot critical"></span><span>offline</span></div>`;
    if (noticeSlot) noticeText(noticeSlot, e.message, 'bad');
    return null;
  }
}
